"""
Convert Fan Ground-Truth Episode Listing into storylines.json
"""

import json
import os

fan_arcs = [
    (1, "Epic Court Scene", "Classic", "Jethalal in court for Tapu's mischief"),
    (2, "Tapu Sonu Balcony Romance", "Classic", "Tapu and Sonu balcony interactions"),
    (3, "Om Babita E Namaha", "Classic", "Jethalal's iconic Babita devotion"),
    (4, "Bagha as Child Labour Inspector", "Classic", "Police & child labour inspector misunderstanding at Gada Electronics"),
    (5, "Entry of Champaklal", "Classic", "Bapuji's arrival in Gokuldham"),
    (7, "Ram Bolo Bhai Ram", "Classic", "Bapuji lost and found at railway station"),
    (10, "I Love You Message to Komal", "Classic", "Wrong SMS sent to Komal bhabhi"),
    (11, "Rasik Bhai Shareholder", "Classic", "Rasikbhai share market emergency"),
    (14, "Jethalal Kidnapped", "Classic", "Thugs kidnap Jethalal from shop"),
    (18, "Champak as Principal", "Classic", "Bapuji goes to Tapu's school as father"),
    (20, "Jaisa Aap Kahe", "Classic", "Chingur Baba remedy backfires on Jethalal"),
    (26, "Society Theft", "Classic", "Theft mystery in Gokuldham"),
    (33, "Ahsahyog Andolan (Husbands vs Wives)", "Classic", "Patni Pidith Sang non-cooperation movement"),
    (45, "Kidney Sheikh Scam", "Classic", "Organ trafficking confusion with Sheikh"),
    (58, "Sundar Ladies Scheme 1 Ka 2", "Classic", "Sundar's double-your-money investment scheme"),
    (64, "Bagha as Teacher", "Classic", "Bagha tuition teacher episode"),
    (68, "Sweety Extortion Trap", "Classic", "Sweety claims fake affair with Jethalal"),
    (75, "Tapu Ki Shaadi Arc", "Classic", "Tapu's child marriage proposal & dream sequence"),
    (85, "Drunk Sodhi on Terrace", "Classic", "Sodhi locked out and sitting on building roof"),
    (88, "Makarsankranti Jetha vs Sodhi", "Classic", "Kite flying competition between Jethalal and Sodhi"),
    (91, "Dr. Hathi Stuck in Auto", "Classic", "Dr. Hathi physically stuck inside auto-rickshaw"),
    (112, "Kaam Wali Bai Crisis", "Classic", "Maid crisis in Gokuldham"),
    (129, "Tapu Exam Paper Leak", "Classic", "Tapu Sena paper leak scare"),
    (130, "Iyer Babita Fake Fight (April Fool)", "Classic", "April fool fake divorce prank by Iyer and Babita"),
    (134, "Dental Checkup Camp", "Classic", "Dentist camp in Gokuldham"),
    (138, "Aye Blue Saree", "Classic", "Jethalal's blue saree confusion"),
    (139, "Minakshi Washing Powder", "Classic", "Washing powder promotion scam"),
    (144, "Tiku Jini Wadi Picnic", "Classic", "Gokuldham picnic to Tiku Jini Wadi waterpark"),
    (151, "Kitty Party & Daya-Madhavi Fight", "Classic", "Kitty party feud between Mahila Mandal"),
    (162, "Chor in Society (Khujli Powder)", "Classic", "Thief in Gokuldham captured by Tapu Sena's itching powder"),
    (167, "Popatlal's Epic First Entry", "Classic", "Journalist Popatlal enters Gokuldham Society"),
    (175, "Gokuldham Premier League (GPL 1)", "Classic", "Jetha Ke Janbaaz vs Daya Ke Daredevils"),
    (184, "The Bhootni Arc in Gokuldham", "Classic", "Ghost in white saree haunts Gokuldham"),
    (190, "Babilly Boy Arc", "Classic", "Babilly boy adoption scare"),
    (200, "Jethalal In London Trip", "Classic", "Jethalal wins trip to London"),
    (230, "Keri Mangoes Arc", "Classic", "Keri mango box confusion"),
    (244, "Popatlal Weds Keri", "Classic", "Popatlal's marriage attempt with Keri"),
    (250, "Red Cherry Mobile Arc", "Classic", "Popatlal's red cherry phone"),
    (260, "Tapu Sena TV Advertisement", "Classic", "Tapu Sena acts in TV commercial"),
    (275, "Champak-Jetha Shoes Swap", "Classic", "Bapuji's shoe size mix-up"),
    (278, "Swimming Pool Special", "Classic", "Gokuldham men learn swimming"),
    (284, "Hotel Blue Queen (Baka Entry)", "Classic", "Baka's iconic entry at Hotel Blue Queen"),
    (294, "Jow Tea & Sharab Confusion", "Classic", "Tea vs alcohol misunderstanding"),
    (296, "Popatlal Nanga Balcony", "Classic", "Popatlal locked on balcony"),
    (300, "TMKOC In Ahmedabad", "Classic", "Gokuldham visits Daya's home in Ahmedabad"),
    (310, "Bhide's New Computer", "Classic", "Bhide buys a computer for tuition"),
    (328, "Holi in Mahabaleshwar", "Classic", "Holi celebration trip to Mahabaleshwar"),
    (335, "Truck Stuck in Gokuldham Gate", "Classic", "Massive truck blocks Gokuldham entrance"),
    (341, "Jal Devta Arc", "Classic", "Jal Devta water blessing incident"),
    (346, "Sonu's Parents Teacher Meeting", "Classic", "Bhide's PTM stress for Sonu"),
    (355, "Saudi Arabia Gold Scam", "Classic", "Fake Saudi gold deal"),
    (362, "Garba Andolan", "Classic", "Mahila Mandal Garba protest"),
    (368, "Society Sports Games", "Classic", "Gokuldham sports tournament"),
    (374, "Chai Piyo Biscuit Khao", "Classic", "Iconic Bhide & Jethalal tea quarrel"),
    (378, "Builder Black Money Scam", "Classic", "Builder black money extortion"),
    (384, "Sai Bhakt Mandal", "Classic", "10-10 bucket water bath incident"),
    (387, "Water Shortage & Tanker Crisis", "Classic", "Gokuldham water pipeline failure & tanker arrival"),
    (390, "Gokuldham Premier League (GPL 2)", "Golden", "GPL Season 2 cricket extravaganza"),
    (412, "Jethalal Hair Loss Arc", "Golden", "Jethalal wig and hair loss crisis"),
    (416, "Famous Bhootni Renovation Arc", "Golden", "Mohanlal flat ghost haunting"),
    (480, "Koyal Marriage Arc", "Golden", "Popatlal's wedding proposal with Koyal"),
    (487, "Daya Dahi Handi Stunt", "Golden", "Daya climbs human pyramid for Dahi Handi"),
    (495, "Peter Fernandes Fraud Case", "Golden", "Peter Fernandes land fraud case"),
    (500, "Credit Card Shopping Scam", "Golden", "Popatlal credit card fraud"),
    (515, "Gokuldham Building Painting", "Golden", "Society exterior painting fight"),
    (538, "Tapu Bald Haircut (Ganja)", "Golden", "Tapu shaved head punishment"),
    (556, "World Cup Hawan", "Golden", "Special prayer hawan for India World Cup win"),
    (565, "Bum Bum Bola (Bhang Special)", "Golden", "Holi Bhang intoxication episode"),
    (568, "Sundar Hides at Jetha's House", "Golden", "Sundar hiding during Holi"),
    (576, "Iyer Transfer & Farewell Party", "Golden", "Iyer Chennai transfer scare & farewell"),
    (608, "Bhide Mango Business", "Golden", "Bhide's Ratnagiri Alphonso mango business"),
    (617, "Bhook Hartaal Hunger Strike", "Golden", "Gokuldham hunger strike"),
    (625, "Gokuldham Khel Mahotsav (GKM)", "Golden", "Gokuldham Olympic games"),
    (640, "Chaddi Gang Robbery Arc", "Golden", "Notorious Chaddi Gang breaks into Gokuldham"),
    (660, "Popatlal Umbrella Birthday", "Golden", "Popatlal's umbrella birthday surprise"),
    (704, "Wooden Horse Statue Arc", "Golden", "Ghode ki murti incident"),
    (730, "Bhide Lottery Ticket Arc", "Golden", "Bhide wins jackpot lottery ticket"),
    (750, "Mallika Mobile (Babita Fake Friend)", "Golden", "Babita's fraudulent friend Mallika"),
    (765, "Jethalal Mental Balance Arc", "Golden", "Jethalal acting crazy scare"),
    (778, "Theme Park Waterpark Picnic", "Golden", "Gokuldham amusement park trip"),
    (790, "Rann of Kutch Desert Trip", "Golden", "Gokuldham trip to Gujarat Rann Utsav"),
    (801, "Jethalal Trapped in Pakistan Border", "Golden", "Jethalal crosses Pakistan border on camel"),
    (810, "Popatlal & Senorita Arc", "Golden", "Popatlal romantic affair with Senorita"),
    (820, "Holi at Farmhouse", "Golden", "Gokuldham Holi celebration at resort farmhouse"),
    (836, "New Society Renovation (Sundar)", "Golden", "Sundar renovates Gokuldham Society"),
    (851, "Abdul's New Soda Shop", "Golden", "Abdul inaugurates modernized soda shop"),
    (865, "Gandhi Maidan Protest", "Golden", "Gokuldham protest at Gandhi Maidan"),
    (869, "Babita's Missing Suitcase", "Golden", "Babita's suitcase mix-up"),
    (881, "Jethalal Tubelight Incident", "Golden", "Jethalal tubelight injury"),
    (890, "Bhide Sakharam Scooter Junk Arc", "Golden", "Sakharam sold as scrap metal"),
    (910, "Bal Vivadhan Discussion", "Golden", "Child welfare discussion"),
    (920, "Jethalal Bribe Case", "Golden", "Jethalal bribery trap"),
    (927, "Choco Moco Chocolate Scam", "Golden", "Choco Moco chocolate scheme"),
    (960, "Jadu La Dancer Arc", "Golden", "Gokuldham dance competition"),
    (985, "Chaniya Choli Box Swap", "Golden", "Navratri costume box mix-up"),
    (1016, "Eye Donation Camp", "Golden", "Gokuldham eye donation drive"),
    (1022, "Tan Man Kudrat Upchar Ashram", "Golden", "Jethalal at health wellness resort"),
    (1045, "Sheru Dog In Gokuldham", "Golden", "Stray dog Sheru adopted by Gokuldham"),
    (1075, "Gulabo Kutch Marriage Lawsuit", "Golden", "Gulabo claims marriage with Jethalal"),
    (1125, "Kochi Keri Mango Scam", "Golden", "Kochi mango fraud"),
    (1147, "3 Trucks Blocking Gate", "Golden", "3 trucks parked in front of Gokuldham"),
    (1156, "Khote Classes Coaching Scam", "Golden", "Sonu's coaching institute scam exposed"),
    (1180, "Taarak Mehta Poem Affair", "Golden", "Taarak's poem mistaken for secret lover"),
    (1189, "MAK Associate Fraud", "Golden", "Builder fraud case"),
    (1200, "Gokuldham In Paris Trip", "Golden", "Gokuldham trip to Paris, France"),
    (1237, "Dr. Hathi Stuck Under Tree", "Golden", "Dr. Hathi trapped under fallen tree"),
    (1257, "Champaklal's Unstoppable Hiccups", "Golden", "Bapuji's non-stop hiccup medical emergency"),
    (1266, "Sachin Tendulkar Retirement", "Golden", "Gokuldham tribute to Sachin Tendulkar"),
    (1280, "Onion Black Marketing Arc", "Golden", "Onion price hike & black marketing"),
    (1290, "Popatlal & Bulbul Wedding Arc", "Golden", "Popatlal falls in love with Bulbul"),
    (1326, "Bagha & Bhide Cooker Blast", "Golden", "Pressure cooker explosion in Bhide flat"),
    (1335, "Fitness & Jethalal Lock Incident", "Golden", "Jethalal trapped in fitness gym lock"),
    (1365, "Bandya Scooter Arc", "Golden", "Bhide's scooter repair adventure"),
    (1385, "Amitabh Bachchan Visit to Gokuldham", "Golden", "Amitabh Bachchan visits Gokuldham"),
    (1390, "Coconut Tree Danger Arc", "Golden", "Dangerous coconut tree in compound"),
    (1400, "Sundar Election Campaign", "Golden", "Sundar fights local elections"),
    (1410, "Bhide Natural Nature Camp", "Golden", "Gokuldham eco nature camp trip"),
    (1425, "Gokuldham Premier League (GPL 3)", "Golden", "GPL Season 3 tournament"),
    (1445, "CID Crossover (Ajay Dewan Case)", "Golden", "ACP Pradyuman & CID solve Gokuldham case"),
    (1470, "Gokuldham Hong Kong Trip", "Golden", "Gokuldham vacation to Hong Kong & Disneyland"),
    (1500, "Mumbai Darshan Bus Tour", "Modern", "Gokuldham open-bus Mumbai Darshan tour"),
    (1510, "Cycle Yatra Rally", "Modern", "Gokuldham cycle awareness rally"),
    (1670, "Popatlal Weds Sapna Arc", "Modern", "Popatlal marriage attempt with Sapna"),
    (1690, "Jethalal Winter Sweater Arc", "Modern", "Jethalal's uncomfortable sweater"),
    (1700, "MK Gandhi College Admission", "Modern", "Tapu Sena college admission at MK Gandhi College"),
    (1725, "Tapu Sena College Shopping", "Modern", "Tapu Sena shopping for college style"),
    (1735, "Bawri's Parents Visit to Mumbai", "Modern", "Bagha meets Bawri's parents"),
    (1760, "Gokuldham Grand Renovation", "Modern", "Complete modern renovation of Gokuldham Society"),
    (1830, "Babita Paan Masala Ad Scandal", "Modern", "Babita featured in controversial advertisement"),
    (1850, "Tapu Sena Bunking College", "Modern", "Tapu Sena caught bunking classes"),
    (1860, "Taarak Jethalal Chai Party", "Modern", "Taarak and Jethalal secret tea sessions"),
    (1870, "Bhide Gold Coin Found", "Modern", "Gold coin found during renovation"),
    (1914, "Iyer Babita Fake Divorce Arc", "Modern", "Iyer & Babita fake divorce prank"),
    (1940, "Madhavi Cheap Mango Business", "Modern", "Madhavi's cheap mango wholesale business"),
    (1950, "Bawri & Bagha Engagement (Sagai)", "Modern", "Bagha and Bawri grand engagement ceremony"),
    (1970, "Miss Cycle Competition", "Modern", "Mahila Mandal cycle race competition"),
    (1983, "Jethalal Hand Trapped in Lota", "Modern", "Jethalal's hand stuck inside brass vessel"),
    (2000, "Bawri Eve Teasing Incident", "Modern", "Gokuldham protects Bawri from eve teasers"),
    (2070, "Natu Bagha Salary Strike (Pagaar Andolan)", "Modern", "Natu Kaka and Bagha salary strike"),
    (2170, "Ratnavali Gemstone Arc", "Modern", "Ratnavali tests Gokuldham couples' love"),
    (2225, "Popatlal Tubelight Wedding", "Modern", "Popatlal marriage attempt with Tubelight"),
    (2235, "Gokuldham Vacation in Goa", "Modern", "Gokuldham beach holiday trip to Goa"),
    (2250, "Washing Machine Prize Scam", "Modern", "Lucky draw washing machine scam"),
    (2270, "Komal Weight Loss Challenge", "Modern", "Komal's fitness weight loss program"),
    (2290, "Bhide Notice Board Stolen", "Modern", "Suvichar notice board missing"),
    (2296, "Chai Taka Tak Stall", "Modern", "Taka Tak tea stall competition"),
    (2306, "Cheda Electronics Rivalry", "Modern", "Cheda Electronics attempts to ruin Gada Electronics"),
    (2320, "Golmaal 4 Movie Cast Visit", "Modern", "Ajay Devgn & Golmaal Again cast visit Gokuldham"),
    (2330, "Demonetization Notes in Water Tank", "Modern", "Old currency notes found in society water tank"),
    (2344, "Chintu Kid in Gada Electronics", "Modern", "Naughty kid Chintu creates havoc at shop"),
    (2350, "Bandarpada Gambling Den Raid", "Modern", "Jethalal accidentally trapped in illegal gambling den"),
    (2360, "Bapuji Stuck on Door", "Modern", "Champaklal's neck stuck in wooden door"),
    (2372, "XYZ 007 Secret Agent Case", "Modern", "Gokuldham secret spy mystery"),
    (2378, "Lemon (Nimbu) Theft from Tree", "Modern", "Lemon theft from Gokuldham garden"),
    (2385, "Pinku Parents Mystery Series", "Modern", "The mystery of Pinku's real parents revealed"),
    (2418, "Iyer Chemical Holi Color", "Modern", "Iyer's eco-friendly organic Holi colors"),
    (2445, "Tapu Sena Scooter Accident", "Modern", "Tapu Sena scooter crash panic"),
    (2507, "Jethalal In Senorika Island", "Modern", "Jethalal stranded on Senorika Island"),
    (2530, "Dharavni Dulhan Ghost Arc", "Modern", "Scary bride ghost in Gokuldham"),
    (2557, "New Dr. Hathi Entry", "Modern", "Nirmal Soni re-entry as Dr. Hathi"),
    (2576, "Jethalal Pani Puri Scheme", "Modern", "Jethalal's special pani puri stall scheme"),
    (2590, "Popatlal 1 Crore Lottery Ticket", "Modern", "Popatlal wins 1 crore lottery ticket"),
    (2602, "BYJU'S App Promotion Arc", "Modern", "BYJU'S learning app special episode"),
    (2610, "Jethalal's Gada Electronics Sold", "Modern", "Jethalal forced to sell Gada Electronics"),
    (2635, "Simba Movie Cast Visit", "Modern", "Ranveer Singh & Rohit Shetty visit Gokuldham"),
    (2644, "TMKOC Gujarat Kite Festival", "Modern", "Makar Sankranti in Gujarat with Chief Minister"),
    (2657, "Super X 100 Mobile (Gogi Kaand)", "Modern", "Gogi's expensive smartphone addiction"),
    (2687, "Sonu Leaves Gokuldham", "Modern", "Sonu leaves for higher studies in Pune"),
    (2694, "TMKOC Singapore Vacation", "Modern", "Gokuldham grand holiday trip to Singapore"),
    (2711, "Titto Mobile & Neta Sevaklal Corruption Scam", "Modern", "Gokuldham exposes corrupt politician Sevaklal's election bribe")
]

storylines = []
for idx, arc in enumerate(fan_arcs, 1):
    start_ep = arc[0]
    title = arc[1]
    cat = arc[2]
    desc = arc[3]
    
    # Calculate end episode as start of next arc - 1, or start + 10
    if idx < len(fan_arcs):
        end_ep = fan_arcs[idx][0] - 1
        if end_ep < start_ep:
            end_ep = start_ep
    else:
        end_ep = start_ep + 10
        
    total_eps = end_ep - start_ep + 1
    
    storylines.append({
        "id": f"arc_{start_ep}_{title.lower().replace(' ', '_').replace('(', '').replace(')', '').replace('&', 'and')[:20]}",
        "sortOrder": idx,
        "title": title,
        "tagline": f"Official Ground-Truth Arc (Ep {start_ep} - {end_ep})",
        "description": f"{desc}. Verified official TMKOC ground-truth storyline spanning Episode {start_ep} to Episode {end_ep}.",
        "startEp": start_ep,
        "endEp": end_ep,
        "totalEpisodes": total_eps,
        "category": cat,
        "coverEp": start_ep
    })

out_path = os.path.join(os.path.dirname(__file__), 'storylines.json')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(storylines, f, indent=2)

print(f"SUCCESS! Built master storylines.json with {len(storylines)} ground-truth TMKOC arcs!")
